"""Añadida fecha de vencimiento

Revision ID: 16f232d403e0
Revises: 8c1b56cfd2ab
Create Date: 2026-07-02 21:31:03.003009

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16f232d403e0'
down_revision = '8c1b56cfd2ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('purchase_details', schema=None) as batch_op:
        batch_op.add_column(sa.Column('expiration_date', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('purchase_details', schema=None) as batch_op:
        batch_op.drop_column('expiration_date')

    # ### end Alembic commands ###
