"""actualizar_modelado_modulo_6

Revision ID: 3da48127cd45
Revises: 8e8b77ad821b
Create Date: 2026-08-19 05:33:44.003069

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3da48127cd45'
down_revision = '8e8b77ad821b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventory', schema=None) as batch_op:
        batch_op.add_column(sa.Column('transit_quantity', sa.Numeric(precision=10, scale=2), nullable=False))

    with op.batch_alter_table('movement_details', schema=None) as batch_op:
        batch_op.add_column(sa.Column('received_quantity', sa.Numeric(precision=10, scale=2), nullable=True))
        batch_op.add_column(sa.Column('missing_quantity', sa.Numeric(precision=10, scale=2), nullable=False))

    with op.batch_alter_table('movements', schema=None) as batch_op:
        batch_op.add_column(sa.Column('resolved_by_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('resolution_notes', sa.Text(), nullable=True))
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=30),
               nullable=False)
        batch_op.create_foreign_key(None, 'users', ['resolved_by_id'], ['id'])
        batch_op.drop_column('guide_url')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movements', schema=None) as batch_op:
        batch_op.add_column(sa.Column('guide_url', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('status',
               existing_type=sa.String(length=30),
               type_=sa.VARCHAR(length=20),
               nullable=True)
        batch_op.drop_column('resolution_notes')
        batch_op.drop_column('resolved_by_id')

    with op.batch_alter_table('movement_details', schema=None) as batch_op:
        batch_op.drop_column('missing_quantity')
        batch_op.drop_column('received_quantity')

    with op.batch_alter_table('inventory', schema=None) as batch_op:
        batch_op.drop_column('transit_quantity')

    # ### end Alembic commands ###
