"""Campo is_active añadido a Product_Type

Revision ID: 6a09e797ec6c
Revises: e7576b2ee578
Create Date: 2026-07-20 21:21:17.261175

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a09e797ec6c'
down_revision = 'e7576b2ee578'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_types', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_types', schema=None) as batch_op:
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###
