"""campo quantity eliminado de la tabla products

Revision ID: 87184ede008b
Revises: 6a09e797ec6c
Create Date: 2026-07-28 13:33:27.299359

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '87184ede008b'
down_revision = '6a09e797ec6c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_column('quantity')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
