"""añadido nueva columna lot_number_and_expiration_date_para  movement details y purchase_details

Revision ID: a0d3a77a8e0e
Revises: 3da48127cd45
Create Date: 2026-08-19 17:23:48.331368

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a0d3a77a8e0e'
down_revision = '3da48127cd45'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movement_details', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lot_number', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('expiration_date', sa.Date(), nullable=True))

    with op.batch_alter_table('purchase_details', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lot_number', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('purchase_details', schema=None) as batch_op:
        batch_op.drop_column('lot_number')

    with op.batch_alter_table('movement_details', schema=None) as batch_op:
        batch_op.drop_column('expiration_date')
        batch_op.drop_column('lot_number')

    # ### end Alembic commands ###
