"""Modificaciones Modulo 4 Compras y Divisas

Revision ID: c727cd005ca5
Revises: 9104980da99b
Create Date: 2026-06-13 15:42:47.057680

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c727cd005ca5'
down_revision = '9104980da99b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exchange_rate_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=5), nullable=False),
    sa.Column('rate', sa.Numeric(precision=15, scale=4), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    
    with op.batch_alter_table('purchase_details', schema=None) as batch_op:
        # Renombrado seguro y eliminación de redundancia
        batch_op.alter_column('price_usd', new_column_name='foreign_price')
        batch_op.drop_column('exchange_rate_bcv')

    with op.batch_alter_table('purchases', schema=None) as batch_op:
        # Adición de estatus con valor por defecto
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=False, server_default='COMPLETED'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('purchases', schema=None) as batch_op:
        batch_op.drop_column('status')

    with op.batch_alter_table('purchase_details', schema=None) as batch_op:
        # Reversión segura a su estado original
        batch_op.alter_column('foreign_price', new_column_name='price_usd')
        batch_op.add_column(sa.Column('exchange_rate_bcv', sa.NUMERIC(precision=15, scale=4), autoincrement=False, nullable=True))

    op.drop_table('exchange_rate_history')
    # ### end Alembic commands ###